let allMusic = [
  {
    name: "DJ Wale Babu",
    artist: "Badshah",
    img: "music1",
    src: "music1",
  },
  {
    name: "One Bottle Down",
    artist: "Yo Yo Honey Singh",
    img: "music2",
    src: "music2",
  },
  {
    name: "WAP Feat. Megan Thee Stallion Cardi B",
    artist: "Cardi B",
    img: "music3",
    src: "music3",
  },
  {
    name: "De Una Vez",
    artist: "Selena Gomez",
    img: "music4",
    src: "music4",
  },
  {
    name: "Your Power",
    artist: "Billie Ellish",
    img: "music5",
    src: "music5",
  },
  {
    name: "Laila Main Laila - Raees",
    artist: "Kalyanji – Anandji, JAM8",
    img: "music6",
    src: "music6",
  },
  {
    name: "Sunny Sunny - Yaariyan",
    artist: "Yo Yo Honey Singh",
    img: "music7",
    src: "music7",
  },
  {
    name: "Dilbar - Satyameva Jayate",
    artist: "Dhvani Bhanushali, Neha Kakkar, Ikka Singh, Asees Kaur",
    img: "music8",
    src: "music8",
  },
  {
    name: "Chor Denge",
    artist: "Parampara Tandon, Sachet-Parampara",
    img: "music11",
    src: "music11",
  },
  {
    name: "Blue Eyes",
    artist: "Yo Yo Honey Singh",
    img: "music9",
    src: "music9",
  },
  {
    name: "Garmi - Street Dancer 3D",
    artist: "Badshah, Neha Kakkar",
    img: "music10",
    src: "music10",
  },
  {
    name: "Care Ni Karda - Chalaang",
    artist: "Sweetaj Brar and Yo Yo Honey Singhr",
    img: "music12",
    src: "music12",
  },
  {
    name: "Harley Bird - Home",
    artist: "Jordan Schor",
    img: "music13",
    src: "music13",
  },
  {
    name: "Ikson Anywhere – Ikson",
    artist: "Audio Library",
    img: "music14",
    src: "music14",
  },
  {
    name: "Beauz & Jvna - Crazy",
    artist: "Beauz & Jvna",
    img: "music15",
    src: "music15",
  },
  {
    name: "Hardwind - Want Me",
    artist: "Mike Archangelo",
    img: "music16",
    src: "music16",
  },
  {
    name: "Jim - Sun Goes Down",
    artist: "Jim Yosef x Roy",
    img: "music17",
    src: "music17",
  },
  {
    name: "Lost Sky - Vision NCS",
    artist: "NCS Release",
    img: "music18",
    src: "music18",
  },
];
